# Generated by Django 5.0.3 on 2024-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie',
            field=models.FileField(null=True, upload_to='files/videos'),
        ),
    ]
